server:
  port: 8300

spring:
  elasticsearch:
    rest:
      uris: 119.45.188.14:9200
  application:
    name: search-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/