server:
  port: 8900

spring:
  application:
    name: pay-service

#日志设置
logging:
  level:
    # 打印与我们程序相关的日志信息
    com.baidu.shop: debug
# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

shop:
  worker:
    workerId: 1 # 项目唯一标识
    datacenterId: 1 # 序列号 其实也是唯一标识
  jwt:
    pubKeyPath: D:\feiq\RecvFiles\6_month\shop\token\rea.pub # 公钥地址(私钥加密,公钥解密)
    cookieName: SHOP_TOKEN